cc_binary(
    name = "simple_http_client",
    srcs = [
        "simple_http_client.cpp"
    ],
    deps = [
        "//:viahttplib",
    ],
    linkopts = [
        "-pthread",
        "-lboost_system",
    ]
)
cc_binary(
    name = "example_http_client",
    srcs = [
        "example_http_client.cpp"
    ],
    deps = [
        "//:viahttplib",
    ],
    linkopts = [
        "-pthread",
        "-lboost_system",
    ]
)
